import { Prisma, RecordStatus } from "@prisma/client";
import { StatusBadge } from "@/components/status-badge";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";
type Query = { q?: string; status?: string; source?: string; sort?: string };
export default async function RecordsPage({ searchParams }: { searchParams: Promise<Query> }) {
  const query = await searchParams; const q = query.q?.trim() ?? "";
  const status = Object.values(RecordStatus).includes(query.status as RecordStatus) ? query.status as RecordStatus : undefined;
  const where: Prisma.FinancialRecordWhereInput = { ...(q ? { OR: [{ referenceNumber: { contains: q } }, { source: { contains: q } }] } : {}), ...(status ? { status } : {}), ...(query.source ? { source: query.source } : {}) };
  const orderBy = query.sort === "amount" ? { amount: "desc" as const } : query.sort === "oldest" ? { date: "asc" as const } : { date: "desc" as const };
  const [records, sources] = await Promise.all([prisma.financialRecord.findMany({ where, take: 100, orderBy, include: { decisions: { take: 1, orderBy: { createdAt: "desc" } } } }), prisma.financialRecord.findMany({ select: { source: true }, distinct: ["source"] })]);
  return <section><div className="eyebrow">Source data</div><h1 className="page-title">Financial records</h1><p className="subtle">Search and inspect the reconciled synthetic source data.</p><form className="toolbar"><input className="input" name="q" placeholder="Search reference or source" defaultValue={q}/><select className="select" name="status" defaultValue={query.status ?? ""}><option value="">All statuses</option><option value="RECONCILED">Reconciled</option><option value="EXCEPTION">Exception</option><option value="UNRESOLVED">Unresolved</option></select><select className="select" name="source" defaultValue={query.source ?? ""}><option value="">All sources</option>{sources.map(({ source }) => <option key={source}>{source}</option>)}</select><select className="select" name="sort" defaultValue={query.sort ?? "recent"}><option value="recent">Most recent</option><option value="oldest">Oldest</option><option value="amount">Highest amount</option></select><button className="button">Apply</button><a className="link-button" href="/records">Clear</a><span className="count">{records.length} records shown</span></form><article className="panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>Type</th><th>Amount</th><th>Source</th><th>Status</th><th>Confidence</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{record.referenceNumber}</td><td>{record.type.replaceAll("_", " ")}</td><td>₹{record.amount.toLocaleString()}</td><td>{record.source}</td><td><StatusBadge status={record.status}/></td><td>{record.decisions[0] ? `${Math.round(record.decisions[0].confidence * 100)}%` : "—"}</td></tr>)}</tbody></table></div>{!records.length && <div className="empty">No records match these filters. Clear the filters or try a different reference.</div>}</article></section>;
}
